#!/bin/sh

# This script copies modified information from this directory to a
# CloudLab machine.

target=hp040.utah.cloudlab.us
# rsync -rtv --exclude-from=rsync-exclude.txt ./ $target:/ouster/grpc/
rsync -rtv --exclude-from=rsync_exclude.txt ./ $target:/ouster/grpc_homa/