/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef JNI_H
#define JNI_H

#ifdef _WIN32
#define JNI_EXPORT_FUNC __declspec(dllexport)
#else
#define JNI_EXPORT_FUNC
#endif

#include <string>

namespace jni {
    class Greeter {
        public:
        std::string JNI_EXPORT_FUNC greeting();
    };
}

#endif
